[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[variables]
PUBLIC_BASE_URL = "https://radhey-save-restricted-content-safe-bot-production.up.railway.app"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10